# Generated by Django 5.2.1 on 2025-06-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profile', to='users.profile'),
        ),
        migrations.CreateModel(
            name='ChildRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='users.profile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='users.profile')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.ManyToManyField(related_name='parent_profiles', through='users.ChildRelationship', to='users.profile'),
        ),
    ]
