# Generated by Django 5.2.1 on 2025-06-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_parent_childrelationship_profile_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent',
        ),
    ]
