# Generated by Django 5.2.1 on 2025-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_children_kid_delete_childrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher')], default='parent', max_length=10),
        ),
    ]
