# Generated by Django 5.2.1 on 2025-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='parent', max_length=10),
        ),
    ]
